[build]
publish = "dist"
command = "bun run build"

[build.environment]
NODE_VERSION = "18"
BUN_VERSION = "1.0.0"
# Enable Bun on Netlify
USE_BUN = "true"

# Explicitly disable Next.js plugin since this is a Vite app
[[plugins]]
package = "@netlify/plugin-nextjs"
[plugins.inputs]
disable = true

# SPA routing - redirect all routes to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# API redirects for Supabase functions (if using)
[[redirects]]
from = "/api/*"
to = "https://your-supabase-project.supabase.co/functions/v1/:splat"
status = 200
force = true

[dev]
command = "bun run dev"
port = 5173
